services:
  - type: web
    name: dapp-sqlite-transactions
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CHAIN_ID
        value: "11155111"
      - key: CHAIN_NAME
        value: Sepolia
      - key: CONTRACT_ADDRESS
        value: ""
